//
// Created by 张贺凡 on 2024/11/26.
//

#ifndef LOADABLE_KERNEL_MODULE_VARIABLES_H
#define LOADABLE_KERNEL_MODULE_VARIABLES_H
#define ARRAY_BASED_ROUTING_TABLE_TYPE 1
#define HASH_BASED_ROUTING_TABLE_TYPE 2
#endif //LOADABLE_KERNEL_MODULE_VARIABLES_H
